### ISSUE TITLE
Check log rotation on Windows

### ISSUE THREAD

**Issue by tmtowtdi** [tmtowtdi/MontyLacuna#4]
jof said he had to clear out the log file manually to get his scripts working again.  It sounds like the log filled up but then failed to rotate for whatever reason, and then refused to write more to an already "full" logfile.

Check on windows.

**Comment by tmtowtdi** [comment]
Traceback from jof:

    Traceback (most recent call last):
    File "C:\Python34\lib\logging\handlers.py", line 72, in emit
    self.doRollover()
    File "C:\Python34\lib\logging\handlers.py", line 173, in doRollover
    self.rotate(self.baseFilename, dfn)
    File "C:\Python34\lib\logging\handlers.py", line 113, in rotate
    os.rename(source, dest)
    PermissionError: [WinError 32] The process cannot access the file because it is
    being used by another process: 'C:\\Users\\jof\\MontyLacuna\\var\\us1.log' -> 'C
    :\\Users\\jof\\MontyLacuna\\var\\us1.log.1'
    Call stack:
    File "bin\jof_train_spies.py", line 64, in <module>
    TrainEm(planet)
    File "bin\jof_train_spies.py", line 4, in TrainEm
    securityBuilding = my_planet.get_buildings_bytype('intelligence')[0]
    File "C:\Users\jof\MontyLacuna\bin/../lib\lacuna\body.py", line 339, in get_bu
    ildings_byty...

**Comment by tmtowtdi** [comment]
jof did mention that he only had a single Python script running at the time.

That being said, what happens if I've got a long-running script active, and another script comes along and wants to rotate the logfile?  **needs tested**

**Comment by tmtowtdi** [comment]
clients.py contains three separate log handlers.  All had been writing to the same file.  This wasn't giving me any issues on Ubuntu, but it's what cause the permissions problems on Windows.

All three handlers now write to separate log files, which seems to fix the problem.
